name: fdic
version: 'VERSION'
summary: Dictionary filter for STDIN
description: Dictionary filter for STDIN
grade: stable
confinement: strict

apps:
  fdic:
    command: bin/fdic

parts:
  fdic:
    source: .
    build-packages:
      - g++
    plugin: nil
    override-build: |
      g++ -O3 -std=c++17 -Wall -o fdic fdic.cpp dictionary.cpp
      install -D fdic $SNAPCRAFT_PART_INSTALL/bin/fdic
      install -Dm644 fdic.1 $SNAPCRAFT_PART_INSTALL/man/man1/fdic.1
    stage:
      - bin/fdic
      - man/man1/fdic.1
    prime:
      - bin/fdic
      - man/man1/fdic.1
